// <auto-generated />
using System;
using CosmosPro.ML.DemandForCast.Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmosPro.ML.DemandForCast.Engine.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    [Migration("20260728180358_AddRedes")]
    partial class AddRedes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.CargaStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LinhasImportadas")
                        .HasColumnType("bigint");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_CargasStage_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_CargasStage_Status_DataAgendamento");

                    b.ToTable("CargasStage", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CnpjRaiz")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Redes_Slug");

                    b.ToTable("Redes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "Rede Demo",
                            Slug = "demo"
                        });
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.SimulacaoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CicloDias")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("FatorServico")
                        .HasColumnType("float");

                    b.Property<int>("JanelaDias")
                        .HasColumnType("int");

                    b.Property<int>("LeadTimeDias")
                        .HasColumnType("int");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SeriesSimuladas")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TreinoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreinoJobId")
                        .HasDatabaseName("IX_SimulacoesCompra_TreinoJobId");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_SimulacoesCompra_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_SimulacoesCompra_Status_DataAgendamento");

                    b.ToTable("SimulacoesCompra", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.TreinoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FeaturesGeradas")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxSkus")
                        .HasColumnType("int");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ModeloBlobKey")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_TreinoJobs_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_TreinoJobs_Status_DataAgendamento");

                    b.ToTable("TreinoJobs", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.CargaStage", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.SimulacaoCompra", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.TreinoJob", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
