// <auto-generated />
using System;
using CosmosPro.ML.DemandForCast.Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmosPro.ML.DemandForCast.Engine.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    [Migration("20260827040944_AddCategoriaNoItemDaSessao")]
    partial class AddCategoriaNoItemDaSessao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.CargaStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LinhasImportadas")
                        .HasColumnType("bigint");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_CargasStage_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_CargasStage_Status_DataAgendamento");

                    b.ToTable("CargasStage", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoPbs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("JanelaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("JanelaInicio")
                        .HasColumnType("date");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("TipoCalculo")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TreinoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreinoJobId")
                        .HasDatabaseName("IX_ComparacoesPbs_TreinoJobId");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_ComparacoesPbs_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_ComparacoesPbs_Status_DataAgendamento");

                    b.ToTable("ComparacoesPbs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ComparacoesPbs_TipoCalculo", "[TipoCalculo] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CargaStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComparacaoPbsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MotivoInviabilidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkusSemCadastro")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SugestaoDataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("SugestaoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SugestaoId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SugestaoTipoCalculo")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("TreinoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RedeId", "CriadoEm")
                        .HasDatabaseName("IX_ComparacaoSessoes_Rede_CriadoEm");

                    b.HasIndex("Status", "AtualizadoEm")
                        .HasDatabaseName("IX_ComparacaoSessoes_Status_AtualizadoEm");

                    b.ToTable("ComparacaoSessoes", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessaoItem", b =>
                {
                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("CompraSugeridaMl")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal>("CompraSugeridaPbs")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Curva")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("DemandaDiaMl")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("DemandaDiaPbs")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("DemandaDiaReal")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("JanelaAlemDoHistorico")
                        .HasColumnType("bit");

                    b.Property<string>("NomeProduto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("SobraMlUnidades")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal?>("SobraMlValor")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("SobraPbsUnidades")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.Property<decimal?>("SobraPbsValor")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("VendidoNaJanela")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.HasKey("SessaoId", "LojaId", "Sku");

                    b.ToTable("ComparacaoSessaoItens", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Questionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EnviadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ItensComDecisaoMl")
                        .HasColumnType("int");

                    b.Property<int>("PassoAtual")
                        .HasColumnType("int");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalDeItens")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersaoCatalogo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Questionarios_SessaoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Questionarios_UsuarioId");

                    b.HasIndex("RedeId", "EnviadoEm")
                        .HasDatabaseName("IX_Questionarios_Rede_EnviadoEm");

                    b.ToTable("Questionarios", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.QuestionarioResposta", b =>
                {
                    b.Property<Guid>("QuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerguntaCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OpcaoCodigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OpcaoTexto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OpcaoValor")
                        .HasColumnType("int");

                    b.Property<string>("PerguntaTexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TextoLivre")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("QuestionarioId", "PerguntaCodigo");

                    b.ToTable("QuestionarioRespostas", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CnpjRaiz")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Redes_Slug");

                    b.ToTable("Redes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "Rede Demo",
                            Slug = "demo"
                        });
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.SimulacaoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CicloDias")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("FatorServico")
                        .HasColumnType("float");

                    b.Property<int>("JanelaDias")
                        .HasColumnType("int");

                    b.Property<int>("LeadTimeDias")
                        .HasColumnType("int");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SeriesSimuladas")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TreinoJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreinoJobId")
                        .HasDatabaseName("IX_SimulacoesCompra_TreinoJobId");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_SimulacoesCompra_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_SimulacoesCompra_Status_DataAgendamento");

                    b.ToTable("SimulacoesCompra", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.TreinoJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataAgendamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FeaturesGeradas")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxSkus")
                        .HasColumnType("int");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ModeloBlobKey")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("TreinoAte")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RedeId", "DataAgendamento")
                        .HasDatabaseName("IX_TreinoJobs_Rede_DataAgendamento");

                    b.HasIndex("Status", "DataAgendamento")
                        .HasDatabaseName("IX_TreinoJobs_Status_DataAgendamento");

                    b.ToTable("TreinoJobs", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("RedeId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RedeId")
                        .HasDatabaseName("IX_Usuarios_RedeId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.CargaStage", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoPbs", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessao", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessaoItem", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessao", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Questionario", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.ComparacaoSessao", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.QuestionarioResposta", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Questionario", null)
                        .WithMany()
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.SimulacaoCompra", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.TreinoJob", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Rede", null)
                        .WithMany()
                        .HasForeignKey("RedeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CosmosPro.ML.DemandForCast.Engine.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
