<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>CosmosPro.ML.DemandForCast.ApiService.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.3.4" />
    <PackageReference Include="Refit" Version="10.1.6" />
    <PackageReference Include="Refit.HttpClientFactory" Version="10.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CosmosPro.ML.DemandForCast.AppHost\CosmosPro.ML.DemandForCast.AppHost.csproj" />
    <ProjectReference Include="..\..\CosmosPro.ML.DemandForCast.Worker\CosmosPro.ML.DemandForCast.Worker.csproj" />
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.Tests.Shared\CosmosPro.ML.DemandForCast.Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="FluentAssertions" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
