<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9466b4a0-3fea-4f40-8a72-e7f05ebb8f03</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.ClickHouse" Version="13.3.5" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects" Version="13.1.1" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlServer.Extensions" Version="13.1.1" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Minio" Version="13.3.0" />
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" Version="13.4.3-preview.1.26305.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.ApiService\CosmosPro.ML.DemandForCast.ApiService.csproj" />
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.Web\CosmosPro.ML.DemandForCast.Web.csproj" />
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.Database\CosmosPro.ML.DemandForCast.Database.sqlproj" />
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.OlapSchema\CosmosPro.ML.DemandForCast.OlapSchema.csproj" />
    <ProjectReference Include="..\CosmosPro.ML.DemandForCast.Worker\CosmosPro.ML.DemandForCast.Worker.csproj" />
  </ItemGroup>

</Project>
